### ISSUE TITLE
Nette application v3.1.5 + Nittro nette-bridges v2.1.5 Declaration of Nette\Application\UI\Component::link(string $destination, $args = Array): string must be compatible with Nittro\Bridges\NittroUI\PresenterUtils::link(string $destination, ...$args): string

### ISSUE THREAD

**Issue by klofac** [nittro/nette-bridges#12]
I updated Nette Application to 3.1.5. Problem is : Revert "Component::link() & etc uses variadic parameter"
https://github.com/nette/application/releases/tag/v3.1.5
https://github.com/nette/application/issues/298

Nette v3.1.5 + Nittro v2.1.5 = Compile Error
Nette v3.1.5 + Nittro v2.1.4 = OK
Nette v3.1.4 + Nittro v2.1.5 = OK

Could you fix it again, please ?

**Comment by jahudka** [comment]
Hi, I'm happy to accept a PR ;-)
