### ISSUE TITLE
Fix PresenterUtils declaration for Nette 3.0-dev

### ISSUE THREAD

**Issue by Lumeriol** [nittro/nette-bridges#3]
Opět zdravím, došlo k poměrně rozsáhlému updatu Nette-dev (plný přechod na PHP 7.1), takže je problém s kompatibilitou metod. Zatím jsem našel pouze RedrawControl, ale občas mi to hodilo chybu i s redirect(), kde je deprecated parametr "code", ale to byl pravděpodobně dočasný pokus v Nette to už odstranit. Zatím tedy asi jen toto:

Nette\Application\UI\Control::redrawControl(?string $snippet = NULL, bool $redraw = true): void

Nevím jak to je s NetteForms.js, které je do Nittra implementováno, ale asi pouze starší verze.

**Comment by 2bad2furious** [comment]
Ahoj, 
taky jsem narazil na problém s Utils, a to konkrétně: 
```abstract public function getPresenter(bool $throw = TRUE) : Presenter;```,
 v UI\Presenteru je metoda bez parametru a hází to compileError. 

Verze Bridges: [dev-master](https://github.com/nittro/nette-bridges/commit/4a3511540cd2487334b326c2191f3187d96a46b8)
Verze Nette/Application: v3.0.0-RC1

**Comment by jahudka** [comment]
@2bad2furious pardon za zpoždění, mělo by to být opravené, zkus `nittro/nette-bridges` v2.1.0-alpha4 :-)
