### ISSUE TITLE
Nette application v3.0.1 + Nittro nette-bridges v2.1.2 Declaration must be compatible

### ISSUE THREAD

**Issue by klofac** [nittro/nette-bridges#7]
I updated Nette and Nittro-Bridges but I got error :
Declaration of Nette\Application\UI\Component::redirect($destination, $args = Array): void must be compatible with Nittro\Bridges\NittroUI\PresenterUtils::redirect($destination = NULL, $args = Array): void

I have :
- Nette application v3.0.1
- Nittro nette-bridges v2.1.2

Combination Nette v3.0.0 + Nittro v2.1.1 is ok

Changelog Nette application v3.0.1 :
- Component::redirect() removed $code from signature #220 #221

Changelog Nittro nette-bridges v 2.1.2 :
- Component::redirect() removed $code from signature

But it doesn't work together. What can I do to solve this problem, please ?

**Comment by jahudka** [comment]
Hi, please upgrade to `nittro/nette-bridges` `v2.1.3`, this should now be fixed in that version

**Comment by klofac** [comment]
Hi, now it is ok, thanks.
