### ISSUE TITLE
Update composer nittro/nette-bridges

### ISSUE THREAD

**Issue by jAKErCZ** [nittro/nette-bridges#8]
Hello,
I updated the application with composer and I get this error.
`Compile Error
Declaration of Nette\Application\UI\Presenter::getPresenter($throw = true) must be compatible with Nittro\Bridges\NittroUI\PresenterUtils::getPresenter(): Nette\Application\UI\Presenter`

composer.json
`"require": {
		"php": ">=7.0",
		"nette/application": "^2.4",
		"nette/bootstrap": "^2.4.3",
		"nette/caching": "^2.5",
		"nette/database": "^2.4",
		"nette/di": "^2.4",
		"nette/finder": "^2.4",
		"nette/forms": "^2.4",
		"nette/http": "^2.4",
		"nette/mail": "^2.4",
		"nette/robot-loader": "^2.4 || ^3.0",
		"nette/safe-stream": "^2.3",
		"nette/security": "^2.4",
		"nette/utils": "^2.4",
		"latte/latte": "^2.4",
		"tracy/tracy": "^2.4",
		"dg/adminer-custom": "^1.9",
		"kdyby/translation": "^2.5",
		"ublaboo/datagrid": "^5.6",
		"froala/wysiwyg-editor-php-sdk": "^1.0",
		"contributte/guzzlette": "^2.0",
		"nittro/nette-bridges": "^2.0",
		"nasext/dependent-select-box": "^3.1",
		"kdyby/console": "^2.7",
		"ipub/visual-paginator": "@dev",
		"league/oauth2-client": "^2.4",
		"mpdf/mpdf": "^8.0"`

Please how to fix?

Thx

**Comment by jahudka** [comment]
Hi, your Composer requirements allow the installation of `nittro/nette-bridges` version `2.1` and above - but `2.1` has scalar type hints to be compatible with Nette 3, so you need to constraint your `nittro/nette-bridges` requirement to `2.0.*` - basically replace `"nittro/nette-bridges": "^2.0"` with `"nittro/nette-bridges": "^2.0.0"` in your `composer.json`

**Comment by jAKErCZ** [comment]
Ok i install 

>  - Installing nette/utils (v2.5.3): Downloading (100%)
  - Installing nette/neon (v2.4.3): Downloading (100%)
  - Installing nette/php-generator (v3.2.3): Loading from cache
  - Installing nette/di (v2.4.15): Downloading (100%)
  - Installing nette/bootstrap (v2.4.6): Downloading (100%)
  - Installing nette/finder (v2.5.1): Loading from cache
  - Installing nette/caching (v2.5.8): Downloading (100%)
  - Installing nette/database (v2.4.8): Downloading (100%)
  - Installing nette/mail (v2.4.6): Downloading (100%)
  - Installing nette/robot-loader (v3.1.1): Downloading (100%)
  - Installing nette/safe-stream (v2.4.0): Downloading (100%)
  - Installing nette/security (v2.4.4): Downloading (100%)
  - Installing nette/http (v2.4.11): Downloading (100%)
  - Installing nette/component-model (v2.4.0): Downloading (100%)
  - Installing nette/forms (v2.4.9): Downloading (100%)
  - Installing nette/reflection (v2.4.2): Downloading (100%)
  - Installing nette/application (v2.4.13): Downloading (100%)
  - Installing nasext/dependent-select-box (3.1.4): Downloading (100%)
  - Installing tracy/tracy (v2.6.5): Loading from cache
  - Installing psr/log (1.1.0): Downloading (100%)
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing psr/http-message (1.0.1): Downloading (100%)
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Downloading (100%)
  - Installing guzzlehttp/guzzle (6.4.1): Loading from cache
  - Installing namshi/cuzzle (2.0.3): Downloading (100%)
  - Installing contributte/guzzlette (v2.1.0): Loading from cache
  - Installing dg/adminer-custom (v1.19.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.12.0): Loading from cache
  - Installing symfony/filesystem (v4.3.5): Loading from cache
  - Installing symfony/config (v4.3.5): Loading from cache
  - Installing symfony/translation-contracts (v1.1.7): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.12.0): Loading from cache
  - Installing symfony/translation (v4.3.5): Loading from cache
  - Installing latte/latte (v2.5.3): Loading from cache
  - Installing kdyby/strict-objects (v1.0.0): Downloading (100%)
  - Installing kdyby/translation (v2.6.0): Loading from cache
  - Installing symfony/inflector (v4.3.5): Loading from cache
  - Installing symfony/property-access (v4.3.5): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing ublaboo/responses (v1.0.7): Downloading (100%)
  - Installing ublaboo/datagrid (v5.7.2): Loading from cache
  - Installing froala/wysiwyg-editor-php-sdk (1.1.0): Loading from cache
  - Installing nittro/nette-bridges (v2.1.3): Loading from cache
  - Installing symfony/service-contracts (v1.1.7): Loading from cache
  - Installing symfony/polyfill-php73 (v1.12.0): Loading from cache
  - Installing symfony/console (v4.3.5): Loading from cache
  - Installing kdyby/console (v2.7.1): Downloading (100%)
  - Installing ipub/visual-paginator (v1.0.7): Downloading (100%)
  - Installing league/oauth2-client (2.4.1): Loading from cache
  - Installing myclabs/deep-copy (1.9.3): Loading from cache
  - Installing setasign/fpdi (v2.2.0): Loading from cache
  - Installing mpdf/mpdf (v8.0.2): Loading from cache
  - Installing nette/tester (v2.3.0): Loading from cache
And error again. No fix.

**Comment by jAKErCZ** [comment]
Oh sorry i idiot. Thx for help.
