### ISSUE TITLE
Incompatibility with latte v2.9.0

### ISSUE THREAD

**Issue by obud** [nittro/nette-bridges#9]
LogicException
Invalid tag name 'snippet.id'.

![image](https://user-images.githubusercontent.com/40399469/99320108-2c9c8900-286b-11eb-99c5-c98ff5ab4ee4.png)

**Comment by jahudka** [comment]
Hi, this has already been addressed at [nittro/nittro#40](https://github.com/nittro/nittro/issues/40) - it's a confirmed bug in Latte v2.9.0 and will be fixed in v2.9.1. Thanks for reporting though!
